### ISSUE TITLE
p2p code review ( 11 Feb 2020)

### ISSUE THREAD

**Issue by Kyle-Law** [Kyle-Law/newsweek-clone#3]
Feel free to leave any comments / suggestions :)

**Comment by nyatindopatrick** [comment]
Good work!. I'm impressed the way you implemented the scrolling section with overflow.
I only noticed one flaw with the images in "In the magazine section". They looked stretched, though I'm still not sure of how to fix it with bootstrap.
![Screen Shot 2020-02-11 at 10 21 00](https://user-images.githubusercontent.com/48393059/74217612-008b2080-4cb9-11ea-9e9d-5f21ba5fb665.png)

**Comment by patriciachrysy** [comment]
Good job @Kyle-Law !!! I will just give some few suggestions:
- On the smallest screen size, in the 'more stories section' The text is supposed to wrap around the image. Using float will be more appropriate there
- The latest news section and the footer are breaking on the smallest screen size
- The search bar is going out of the bounds when under 1024px screen size

**Comment by dili021** [comment]
Nothing to add :D well done!

**Comment by Kyle-Law** [comment]
:)
